---
- name: Install docker
  hosts: web1
  become: true

  tasks:
    - name: Uninstall Older versions of Docker
      apt:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
      
    - name: Install packages to allow apt to use a repository over HTTPS 
      apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
      update_cache: true

    - name: Add official Docker GPG key
      apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

    - name: Set up the stable docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
         
    - name: Install docker
      apt:
      name:
        - 'docker-ce' 
        - 'docker-ce-cli' 
        - 'containerd.io' 
        - 'docker-compose-plugin'
      state: present
      update_cahe: true 